### ISSUE TITLE
When to release?

### ISSUE THREAD

**Issue by Amo5** [caojiezhang/CiaoSR#1]
Hi,
When to release the code?😁

**Comment by cddlyf** [comment]
@caojiezhang Hi Jiezhang, do you have any ETA for the code release?

**Comment by kaiq663** [comment]
@caojiezhang Hi, be waiting for the code release.

**Comment by caojiezhang** [comment]
Sorry for my late reply. Recently I focus on another project, so I will
release the code on the weekend or next week.

Amo5 ***@***.***> 于2022年12月12日周一 09:15写道：
