### ISSUE TITLE
About the swinir_net module

### ISSUE THREAD

**Issue by Alidaling** [caojiezhang/CiaoSR#10]
When I run this command "python tools/test.py configs/001_localimplicitsr_swinir_div2k_g1_c64b16_1000k_unfold_lec_mulwkv_res_nonlocal.py pretrain_model/swinir-ciaosr.pth" ，it show the error ”ModuleNotFoundError: No module named 'mmedited.models.backbones.sr_backbones.swinir_net”.

How can I obtain swinir_net module？Can you provide it?Thank you！

**Comment by caojiezhang** [comment]
I have updated the code
