### ISSUE TITLE
Questions about network details?

### ISSUE THREAD

**Issue by CrispyFeSo4** [caojiezhang/CiaoSR#5]
Where can I find the detailed structure of the network? The paper mentioned that the appendix would provide a description of the model's architectural details, but the current version does not include an appendix. It seems that there is a discrepancy between the structure described in the paper and the code??
(For example, the paper does not mention how the CiaoSR structure is integrated with the LTE structure.)

Thank you for your assistance!!

**Comment by caojiezhang** [comment]
CiaoSR does not integrate with LTE
